- NEWS.md
- src/main/java/org/folio/processing/mapping/mapper/reader/record/MarcRecordReader.java
- src/main/java/org/folio/processing/mapping/mapper/writer/common/JsonBasedWriter.java
Fixed Null value if mapped field empty
> MODDICORE-44 Fixed Null value if mapped field empty

- NEWS.md
- src/main/java/org/folio/processing/mapping/mapper/reader/record/MarcRecordReader.java
- src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
1. New condition added.
2. Test created.
3. Minor Refactoring.
> MODDICORE-54: Field mappings: Date picker ###TODAY### logic does not work [BUGFIX]

- NEWS.md
- src/main/java/org/folio/processing/mapping/mapper/writer/common/JsonBasedWriter.java
- src/test/java/org/folio/processing/mapping/writer/JsonBasedWriterUnitTest.java
1.indexOf() changed on lastIndexOf() in repeatable fields.
2. Tests fixed.
3. NEWS updated.
> MODINV-319: Mapping exception in mod-inventory with rules for notes.[BUGFIX]

- src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
> Safe condition to avoid string index out of bounds

- NEWS.md
- src/main/java/org/folio/processing/mapping/mapper/writer/common/JsonBasedWriter.java
- src/main/java/org/folio/processing/value/RepeatableFieldValue.java
- src/test/java/org/folio/processing/mapping/writer/JsonBasedWriterUnitTest.java
1.Mechanism for searching and removed the lowest field from path was created to the JsonBasedWriter.
2.Tests were updated.
> MODDICORE-70: Actions in mapping profile don`t work correctly[BUGFIX]

- NEWS.md
- src/main/java/org/folio/processing/mapping/mapper/writer/common/JsonBasedWriter.java
- src/test/java/org/folio/processing/mapping/writer/JsonBasedWriterUnitTest.java
1. Additional check on empty context - added.
2. Tests for empty context added.
3. NEWS updated.
> MODDICORE-72: Create holdings fails because mapping for holdings statement is not working. [BUGFIX]

- NEWS.md
- src/main/java/org/folio/processing/mapping/mapper/reader/record/MarcRecordReader.java
- src/main/java/org/folio/processing/mapping/mapper/writer/common/JsonBasedWriter.java
- src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
1. Bug was fixed. 
2. Additional check on null added. 
3. Tests added.
> MODDICORE-74: Create holdings fails because mapping for Former holdings ID is not working [BUGFIX]

- NEWS.md
- src/main/java/org/folio/processing/mapping/mapper/reader/record/MarcRecordReader.java
- src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
(cherry picked from commit 0e0efcb0d64d1d59393e424d5d3a721484d97ccf)
> MODDICORE-75 - Two 856 fields smushed into 1 eAccess row in holdings record (#74)

- src/main/java/org/folio/processing/mapping/mapper/writer/common/JsonBasedWriter.java
- src/test/java/org/folio/processing/mapping/writer/JsonBasedWriterUnitTest.java
1. "Find and remove these" action for list values improved. 
2. Tests added.
> MODDICORE-70: Actions in mapping profile don`t work correctly. [BUGFIX]

- NEWS.md
- src/main/java/org/folio/processing/mapping/mapper/reader/record/MarcRecordReader.java
- src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
856$3 not mapping into holdings record
> MODDICORE-81 856$3 not mapping into holdings record

- NEWS.md
- src/main/java/org/folio/processing/matching/reader/MarcValueReaderImpl.java
- src/test/java/org/folio/processing/matching/reader/MarcValueReaderTest.java
1. Mechanism created.
2. Tests added.
3. NEWS updated.
> MODDICORE-76: Add support for wildcard indicators and [empty] indicators to the match engine.

- Jenkinsfile
- NEWS.md
- pom.xml
- src/main/java/org/folio/processing/matching/loader/query/LoadQueryBuilder.java
- src/main/java/org/folio/processing/matching/loader/query/MatchingCondition.java
- src/main/java/org/folio/processing/matching/loader/query/QueryHolder.java
- src/main/java/org/folio/processing/matching/reader/MarcValueReaderImpl.java
- src/test/java/org/folio/processing/matching/loader/LoadQueryBuilderTest.java
Refine identifier matching for Instances: backend
> MODDICORE-88 Refine identifier matching for Instances: backend

- NEWS.md
- pom.xml
- src/main/java/org/folio/processing/events/EventManager.java
- src/main/java/org/folio/processing/events/services/publisher/KafkaEventPublisher.java
Change transport layer implementation to use Kafka
> MODDICORE-82 Change transport layer implementation to use Kafka

- pom.xml
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/ProtectedMarcRecordModifierTest.java
> Revert "Update dependencies (#120)"

- pom.xml
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/ProtectedMarcRecordModifierTest.java
> Revert "Revert "Update dependencies (#120)" (#121)"

- pom.xml
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/ProtectedMarcRecordModifierTest.java
> Revert "Revert "Revert "Update dependencies (#120)" (#121)" (#123)"

- NEWS.md
- src/main/java/org/folio/processing/mapping/MappingManager.java
- src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java
**Overview:** This is reproducing in dev envs (testing, snapshot, etc.) and not reproducing in Iris Bugfest, so probably it was caused by MODDICORE-128.
**Approach:** Added constructing location name + location code for accepted values (as it is in the real-envs)
**More info:** https://issues.folio.org/browse/MODDICORE-135
> MODDICORE-135: Holdings fails to create due to Location code not being recognized [BUGFIX]

- src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java
- src/test/java/org/folio/processing/mapping/HoldingsMappingTest.java
- src/test/java/org/folio/processing/mapping/functions/NormalizationFunctionTest.java
Fix HoldingsType mapping
Return empty string instead of null
> MODDICORE-216 Fix HoldingsType mapping

- NEWS.md
- src/main/java/org/folio/processing/events/services/publisher/KafkaEventPublisher.java
- src/test/java/org/folio/processing/events/services/publisher/KafkaEventPublisherTest.java
> MODDATAIMP-491: Improve logging to be able to trace the path of each record and file_chunks.

- src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/ProtectedMarcRecordModifierTest.java
Make MarcRecordModifier support MARC Authority
> MODDICORE-237 Make MarcRecordModifier support MARC Authority

- ramls/authority.json
- src/test/resources/org/folio/processing/mapping/authorityRules.json
- src/test/resources/org/folio/processing/mapping/mappedAuthorityRecord.json
- src/test/resources/org/folio/processing/mapping/parsedAuthorityRecord.json
For correct MARC-to-Authority mapping several fields should be renamed:
* sftGeographicTerm -> sftGeographicName
* saftGeographicTerm -> saftGeographicName
> MODDICORE-244 Update Authority schema

- ramls/instance.json
- src/test/resources/org/folio/processing/mapping/instances.json
1. "administrativeNote" added to the instance schema.
> MODINV-679: Updating an instance with data import erases administrative note.

- NEWS.md
- pom.xml
- src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java
1. First scenario fixed.
2. Test added.
> MODDICORE-272: Protected fields are being removed from the incoming record on import.

- NEWS.md
- pom.xml
- ramls/settings/authoritysourcefile.json
- ramls/settings/authoritysourcefiles.json
- src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java
- src/main/java/org/folio/processing/mapping/defaultmapper/processor/parameters/MappingParameters.java
- src/test/java/org/folio/processing/mapping/functions/NormalizationFunctionTest.java
Create function to populate an Authority Source file ID.
[MODDICORE-276](https://issues.folio.org/browse/MODDICORE-276)
- Schema for Authority Source File added
- SET_AUTHORITY_SOURCE_FILE_ID function implemented
- Tests for SET_AUTHORITY_SOURCE_FILE_ID function added
> MODDICORE-276 Create function to populate an Authority Source file ID

- src/main/java/org/folio/processing/mapping/defaultmapper/processor/parameters/MappingParameters.java
Revert this pull request: https://github.com/folio-org/data-import-processing-core/pull/227
> Revert MODDICORE-280 Unignore authoritySourceFiles json field

- ramls/settings/authoritysourcefile.json
to update Authoritysourcefile.json schema in accordance with PR https://github.com/folio-org/mod-inventory-storage/pull/818
in the mod-inventory-storage to fix data-import  functionality
> Updated Authoritysourcefile schema in accordance with schema in mod-inventory-storage

- PULL_REQUEST_TEMPLATE.md
- src/main/resources/log4j2.properties
Logging improvement - Configuration
Jira: https://issues.folio.org/browse/MODDICORE-289
> [MODDICORE-289] Logging improvement - Configuration

- NEWS.md
- src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java
- src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
Multiple item notes not showing on UI
Added handling accepted values for repeatable fields 
Jira: https://issues.folio.org/browse/MODDICORE-294
> [MODDICORE-294] Added handling accepted values for repeatable fields

- pom.xml
Updated folio-kafka-wrapper to 2.7.0
Bumped folio-kafka-wrapper version
> [KAFKAWRAP-33] Updated folio-kafka-wrapper to 2.7.0

- pom.xml
- ramls/settings/account.json
- ramls/settings/address.json
- ramls/settings/agreement.json
- ramls/settings/alias.json
- ramls/settings/changelog.json
- ramls/settings/email.json
- ramls/settings/organization.json
- ramls/settings/organization_collection.json
- ramls/settings/phone_number.json
- ramls/settings/url.json
- src/main/java/org/folio/processing/mapping/defaultmapper/processor/parameters/MappingParameters.java
Add organizations to MappingParameters
Created new entities Organization and OrganizationCollection
> [MODORDERS-844] Add organizations to MappingParameters

- NEWS.md
- pom.xml
- src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java
- src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Release v4.0.2
[MODDICORE-313](https://issues.folio.org/browse/MODDICORE-313)
> MODDICORE-313 Release data-import-processing-core v4.0.2 Orchid Bug Fix (R1 2023)

- src/main/java/org/folio/processing/mapping/MappingManager.java
- src/test/java/org/folio/processing/mapping/manager/MappingManagerUnitTest.java
https://issues.folio.org/browse/MODDICORE-304
Import statistical code values based on the text
Replace old mapping on new in MappingManager class
> [MODDICORE-304]Cannot import statistical code values based on the text

- src/main/java/org/folio/processing/mapping/MappingManager.java
- src/test/java/org/folio/processing/mapping/manager/MappingManagerUnitTest.java
Mapping string values from accepted values doesn't work
Do not override accepted values if incoming accepted values contain a string value
> [MODDICORE-304] Allow matching string values from incoming accepted values

- pom.xml
Bump version of folio-kafka-wrapper to v2.7.1
> Update folio-kafka-wrapper to v2.7.1

- src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java
- src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Fix bug when cannot add multiple uncontrolled subfields to a linked "MARC bib" field
Update all uncontrolled subfields to all subfields with same code
> MODDICORE-326 Update all subfield to all subfields with same code

- src/main/java/org/folio/processing/mapping/defaultmapper/processor/parameters/MappingParameters.java
Extend MappingParameters with linking rules
- Extend MappingParameters with linking rules
[MODSOURMAN-974](https://issues.folio.org/browse/MODSOURMAN-974)
> MODSOURMAN-974 MARC bib $9 handling | Remove $9 subfields from linkable fields

- .github/workflows/api-schema-lint.yml
- README.md
- ramls/settings/organization.json
Use GitHub Workflows for [api-schema-lint](https://dev.folio.org/guides/describe-schema/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 MODDATAIMP-817 Use GitHub Workflows api-schema-lint

- src/main/java/org/folio/processing/mapping/mapper/mappers/HoldingsMapper.java
- src/main/java/org/folio/processing/mapping/mapper/mappers/ItemMapper.java
- src/test/java/org/folio/processing/mapping/mapper/HoldingsMapperTest.java
- src/test/java/org/folio/processing/mapping/mapper/ItemMapperTest.java
Allow mapping multiple items/holdings from the context
Changed order of 'if' statements, to check if context contains entity first
> [MODDICORE-340] Allow mapping multiple items/holdings from context

- src/main/java/org/folio/processing/matching/matcher/HoldingsItemMatcher.java
_To be able to match by an array of entities represented in json String, not only by a single entity._
_Make deserialization of the input json string as an array of objects and if it fails deserialize as a single object._
**Follow-up PR:** https://github.com/folio-org/mod-inventory/pull/613
> MODINV-862: Add support for json array of entities represented in String

- NEWS.md
- src/test/java/org/folio/processing/events/EventManagerUnitTest.java
- src/test/java/org/folio/processing/events/handlers/CreateInstanceEventHandler.java
Remove step of initial saving of incoming records to SRS
Migrate from DI_SRS_MARC_BIB_RECORD_CREATED to DI_INCOMING_MARC_BIB_RECORD_PARSED event
[MODSOURMAN-1022](https://issues.folio.org/browse/MODSOURMAN-1022)
> MODSOURMAN-1022: migrate from DI_SRS_MARC_BIB_RECORD_CREATED to DI_INCOMING_EDIFACT_RECORD_PARSED event

- src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java
a check has been added  that mapping rule name is not null to fix tests in the dependent module
> MODDICORE-368 - Added check that mapping rule name is not null to fix tests

- ramls/settings/authoritysourcefile.json
DI stuck
updating the schema modified in scope of MODELINKS-123
> MODELINKS-123: Adjust Authority Source Files POST API to restrict creating only local files

- NEWS.md
- src/main/java/org/folio/processing/events/services/publisher/KafkaEventPublisher.java
OOM issue in mod-inventory
[MODINV-944](https://folio-org.atlassian.net/browse/MODINV-944)
close opened producer
> MODINV-944 OOM issue in mod-inventory

- NEWS.md
- src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java
- src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
_Describe the purpose of the pull request. Include background information if necessary._
_How does this change fulfill the purpose?_
> MODDICRE-402: Empty values created in JSON when no fallback value is provided in Instance field mapping for Nature of Content term (Poppy CSP)

- src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java
- src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
[MODDICORE-388](https://folio-org.atlassian.net/browse/MODDICORE-388) Allow to map vendor details with code that contains brackets during order creation
> MODDICORE-388 Allow to map vendor details with code that contains brackets during order creation

- src/main/java/org/folio/processing/events/EventManager.java
- src/main/java/org/folio/processing/mapping/MappingManager.java
- src/main/java/org/folio/processing/matching/MatchingManager.java
- src/test/java/org/folio/processing/events/EventManagerUnitTest.java
- src/test/java/org/folio/processing/events/handlers/CreateHoldingsRecordEventHandler.java
- src/test/java/org/folio/processing/events/handlers/CreateInstanceEventHandler.java
- src/test/java/org/folio/processing/events/handlers/CreateItemRecordEventHandler.java
- src/test/java/org/folio/processing/events/handlers/InstancePostProcessingEventHandler.java
- src/test/java/org/folio/processing/events/handlers/UpdateInstanceEventHandler.java
- src/test/java/org/folio/processing/mapping/manager/MappingManagerUnitTest.java
- src/test/java/org/folio/processing/matching/manager/MatchingManagerTest.java
- src/test/java/org/folio/processing/matching/matcher/HoldingsItemMatcherTest.java
Update raml storage
Updated raml storage
> [MODSOURCE-773] Update raml storage

- README.md
- ramls/authorityExtended.json
- src/main/java/org/folio/processing/mapping/defaultmapper/processor/Processor.java
- src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java
- src/test/resources/org/folio/processing/mapping/authority/mappedRecordExtended.json
_Describe the purpose of the pull request. Include background information if necessary._
_How does this change fulfill the purpose?_
> [MODINV-1071] Extended authorities mapping

- pom.xml
- ramls/settings/acquisition_method.json
- ramls/settings/acquisition_method_collection.json
- ramls/settings/acquisitions_unit.json
- ramls/settings/acquisitions_unit_collection.json
- ramls/settings/expense_class.json
- ramls/settings/expense_class_collection.json
- ramls/settings/fund.json
- ramls/settings/fund_code.json
- ramls/settings/fund_collection.json
- src/main/java/org/folio/processing/mapping/defaultmapper/processor/parameters/MappingParameters.java
- src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java
- src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
Add orders mapping parameters
Extend mapping params with other ref data necessary for Orders mappings
https://folio-org.atlassian.net/browse/MODORDERS-1181
> [MODORDERS-1181] Add orders mapping parameters

- .github/workflows/build-dependants.yml
Add mod-orders build dependence
> Add mod-orders to build-dependants.yml

- src/test/java/org/folio/processing/mapping/InstanceMappingTest.java
- src/test/resources/org/folio/processing/mapping/instance/rules.json
Test subject type mapped if no second id
Modified test to be actual
> [MODSOURMAN-1227] Test subject type mapped if no second id

- .github/workflows/build-dependants.yml
use latest version of download-artifact instead of specific version which can become out-of-date
> Apply latest version of download-artifact

- NEWS.md
- src/main/java/org/folio/processing/events/services/publisher/KafkaEventPublisher.java
- src/main/java/org/folio/rest/util/OkapiConnectionParams.java
- src/test/java/org/folio/processing/events/services/publisher/KafkaEventPublisherTest.java
Add userId to event header and allow to send events with null token
> MODDICORE-433 Add userId to event header and allow to send events with null token

- .github/workflows/build-dependants.yml
- src/main/java/org/folio/processing/events/services/publisher/KafkaEventPublisher.java
[MODDICORE-439](https://folio-org.atlassian.net/browse/MODDICORE-439) Add jobexecution id to kafka headers
* add jobExecutionId into kafka event
> MODDICORE-439 Add jobexecution id to kafka headers

- src/main/java/org/folio/processing/mapping/mapper/writer/common/JsonBasedWriter.java
- src/test/java/org/folio/processing/mapping/mapper/writer/JsonBasedWriterUnitTest.java
[MODDICORE-428](https://folio-org.atlassian.net/browse/MODDICORE-428) Error appeared when in donor field for order field mapping profile user set 2 incorrect values
* skip empty repeatable field value during mapping
* add test
> MODDICORE-428 Error appeared when in donor field for order field mapping profile user set 2 incorrect values
