folio-org/data-import-processing-core

NEWS.md, src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java, src/test/java/org/folio/processing/mapping/functions/NormalizationFunctionTest.java
Remember first byte of the Leader is 00, so byte 7 is actually the 8th position.
In the int_resource file, the leader is LDR 01743nai a2200409 i 4500, and we should be using the "i" in position 7 as the guide, which leads to mode of issuance = integrating resource
=> MODDICORE-51 "Mode of issuance" values not assigned correctly using marc-to-instance map

NEWS.md
=> MODDICORE-66: Mapping exception in mod-inventory with rules for notes [BUGFIX]

NEWS.md, src/main/java/org/folio/processing/mapping/mapper/reader/record/MarcRecordReader.java, src/main/java/org/folio/processing/mapping/mapper/writer/common/JsonBasedWriter.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java, src/test/java/org/folio/processing/mapping/writer/JsonBasedWriterUnitTest.java
1.Added mechanism for passing DELETE_EXISTING action if subfields are empty in repeatable fields.
2. Tests added.
3. NEWS updated.
=> MODDICORE-61: Field mappings: Repeatable fields dropdown action without subfields support.

NEWS.md, PERSONAL_DATA_DISCLOSURE.md
Add personal data disclosure form.
Places a copy of the personal data disclosure form at the top level of the module github repository and checked the boxes that apply.
More info: https://issues.folio.org/browse/MODDICORE-111
=> MODDICORE-111:Add personal data disclosure form.

src/main/java/org/folio/processing/events/EventManager.java
Improving DI_ERROR event for writing information to the log according MODINVSTOR-384
Fixing the commands queue in the method for preparing DI_ERROR event
[MODINVSTOR-384](https://issues.folio.org/browse/MODINVSTOR-384)
=> MODSOURMAN-384: fix the operation queue for preparing the DI_ERROR event

NEWS.md, src/main/java/org/folio/processing/mapping/mapper/writer/common/JsonBasedWriter.java, src/test/java/org/folio/processing/mapping/mapper/writer/JsonBasedWriterUnitTest.java
To make able mapping invoice's "adjustments" and "fundDistributions" within them
* expand `JsonBasedWriter` logic to support nested repeatable field values
* cover by test
* invoice schema: https://github.com/folio-org/acq-models/blob/master/mod-invoice-storage/schemas/invoice.json
* adjustment schema: https://github.com/folio-org/acq-models/blob/ca1b0752b038f98cdb76ee5327772bc5f561385e/mod-invoice-storage/schemas/adjustment.json
=> MODDICORE-116 - Support for invoice adjustments mapping

NEWS.md, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
The main goal is to fix a bug related "permanentLocationId" for the holdings. There is "contains"-logic that can retrieve invalid location from mappingParameters, if there is a piece of the needed location-code.
Contains logic was removed. But there is some complexity regarding this retrieving. 
For example, there is value from MARC-file, which indicates location code: "KU/CC/DI/M". 
And in mapping parameters (from inventory-storage) there will be this string: "Main Library (KU/CC/DI/M)".
So, simple "equals"-logic is invalid here. There should be retrieved specific code from brackets and after that, equals should be applied. Moreover, there can be a case when in MARC-file we will have this value: "(KU/CC/DI/M)" (with brackets). This case was covered too.
1. New mechanism for brackets was …
=> MODDICORE-127: Location code-Loan type assignment problems [BUGFIX]

NEWS.md, src/main/java/org/folio/processing/mapping/MappingManager.java, src/test/java/org/folio/processing/mapping/manager/MappingManagerUnitTest.java
Holdings fails to create due to Location code not being recognized.
Fill Permanent and Temporary Locations in MappingProfile from context MAPPING_PARAMS.
[MODDICORE-128](https://issues.folio.org/browse/MODDICORE-128)
=> MODDICORE-128: Holdings fails to create due to Location code not being recognized

pom.xml, src/main/java/org/folio/processing/mapping/defaultmapper/MarcToInstanceMapper.java
While using data-import-processing-core as a dependency we were unable to map any records to instances that had a list in which used codehaus StringUtils isNotEmpty as a filter. It would just silently fail and hang. Occurred both on a Windows development machine and on infrastructure.
=> MODDICORE-163 Use reliable apache commons

NEWS.md, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
There are cases when data import matches to the first possible location in the list instead of the exact location. The root cause of this issue is that there were created some universities with brackets inside location "name", not only "code"(For example: "Test Olin (Olin) (olin,ils)"). From the previous implementation, it retrieves from brackets value and compares it. That's why it matches with the invalid location. 
1. There was added an improvement for retrieving value only from the last brackets (there will be always "code"-value)
2. Tests added.
3. NEWS.md updated.
More info: https://issues.folio.org/browse/MODDICORE-165
=> MODDICORE-165: Data import matches to first possible location in list  instead of exact location.

NEWS.md, src/main/java/org/folio/processing/mapping/defaultmapper/processor/parameters/MappingParameters.java, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
When calculating ##TODAY## in a profile run at the end of the day, data import used the next day's date. Perhaps not using DST correctly. Observed on Cornell's tenant which is America/New York.
Created brand new mechanism:
1. Retrieve tenant configuration from "/configurations/entries" in srm. There will be a current timezone for the tenant. (By default, it is empty, so it'll proceeded with UTC-timezone). Put this into MappingParameters to the dataImportEventPayload.
2. In di-core while processing ##TODAY##-expression retrieve from dataImportEventPayload current timezone for the tenant, calculate current dateTime in UTC(default) and convert to the timezone for the tenant.
**This PR should be merged together with: https://github.com/folio-org/mod-source-record-manager/pull/458** …
=> MODDICORE-166: Near the day boundary data import calculates today incorrectly.

NEWS.md, src/main/java/org/folio/processing/events/services/processor/EventProcessorImpl.java
This is necessary to keep the mod-srs logs clean.
- Lowering the logging level in EventProcessorImpl will display their mod-srs at the info level and will not interfere if the handler is not detected.
https://issues.folio.org/browse/MODSOURCE-340
=> Modsource 340

src/test/resources/org/folio/processing/mapping/instances.json, src/test/resources/org/folio/processing/mapping/rules.json
In scope of adding Cancelled system control number as resource identifier type:
-	Updated mapping rules and instances to run tests for marc bibs with 019$a and 035$z subfields values;
https://issues.folio.org/browse/MODSOURMAN-563
=> MODSOURMAN-563 Add MARC-Instance field mapping for Cancelled system control number

src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java, src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunctionRunner.java, src/test/java/org/folio/processing/mapping/functions/NormalizationFunctionTest.java
Return null instead of stub uuid for SET_HOLDINGS_TYPE_ID action
- change verification in the SET_HOLDINGS_TYPE_ID 
https://issues.folio.org/browse/MODDICORE-216
=> MODDICORE-216 Cannot edit a MARC Holdings record created with Add MARC Holdings record

NEWS.md, src/main/java/org/folio/processing/events/services/publisher/KafkaEventPublisher.java, src/test/java/org/folio/processing/events/services/publisher/KafkaEventPublisherTest.java
Improve logging to be able to trace the path of each record and file_chunks.
_ChunkId added and put this to kafkaHeaders.
https://issues.folio.org/browse/MODDATAIMP-491
=> MODDATAIMP-491: Improve logging to be able to trace the path of each record and file_chunks.

pom.xml, src/test/java/org/folio/processing/events/utils/PomReaderUtilTest.java
Update mod-pubsub-client from 2.0.0 to 2.4.0 fixing
machine-in-the-middle (MITM) attack during build time (CVE-2021-26291).
=> MODDICORE-228: mod-pubsub-client 2.4.0 fixing build failure

src/main/java/org/folio/processing/matching/loader/query/LoadQueryBuilder.java, src/main/java/org/folio/processing/matching/loader/query/MatchingCondition.java, src/test/java/org/folio/processing/matching/loader/LoadQueryBuilderTest.java
Fix construct cql queries for identifier when change "exactly matches" matching criteria.
- Finding entry into the query holder identifier with matching criteria "exactly matches"
- Seting cqlQuery in new format 
**/inventory/instances?query=(identifiers= /@value/@identifierTypeId=8261054f-be78-422d-bd51-4ed9f33c3422 (785633))** instead of 
**{{baseUrl}}/inventory/instances?query=identifiers=""\""identifierTypeId\"":\""8261054f-be78-422d-bd51-4ed9f33c342\"""" AND (identifiers=""\""value\"":\""785633\"""")**
for an accurate search inside the array
https://issues.folio.org/browse/MODDICORE-231
Meets the requirements of the first two requirements, the third was added after the start of work on the task
=> MODDICORE-231 Data Import matches on identifier type and identifier value separately, resulting in incorrect matches (Kiwi BF)

.github/workflows/build-dependants.yml
https://issues.folio.org/browse/MODDICORE-227
mod-inventory master and mod-source-record-manager master depend on the latest -SNAPSHOT of data-import-processing-core master.
A change in data-import-processing-core master might break the dependent modules.
This GitHub actions workflow automatically verifies that the dependent modules still successfully build when using the new data-import-processing-core artifact. GitHub will run the workflow when a pull request for master is opened or when a commit to master is merged.
See https://issues.folio.org/browse/MODINV-587 why this is needed.
=> MODDICORE-227: GitHub Actions verifying -SNAPSHOT dependants

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java
[MODDICORE-241](https://issues.folio.org/browse/MODDICORE-241)
- Remove unUpdated repeatable controlFields
=> MODDICORE-241 Kiwi: MARC 007 is retained although overlay does not contain MARC 007 field

NEWS.md, src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java
[MODDICORE-242](https://issues.folio.org/browse/MODDICORE-242)
- Remove unUpdated repeatable controlFields
=> MODDICORE-242 MARC 007 is retained although overlay does not contain MARC 007 field

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java
**Overview**
The main issue was that if there are some fields with the same subfield, code, and tag, and if this field is protected - then it will appear twice(duplicated).
**Approach**
Additional condition added.
=> MODDICORE-252: Data Import Update SRS duplicates protected fields on update when there is more than one of any given tag.

NEWS.md, src/main/java/org/folio/processing/events/EventManager.java
Mod-inventory wraps DuplicateEventException into CompletionException, so we need to change data-import-processing-core to check cause instead. Details on the screen below:
For EventHandlerNotFound we don't need such changes because this exception throwing without any wrapping like this:
=> MODINV-671. Check and fix the sending of DI_ERROR after DuplicateEventException appears

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java
to allow addition of incoming fields which matches protection settings to record during the record update
[MODINV-686](https://issues.folio.org/browse/MODINV-686)
[MODDICORE-265](https://issues.folio.org/browse/MODDICORE-265)
=> MODINV-686 - Fixed addition of incoming fields which matches protection settings

src/main/java/org/folio/processing/mapping/defaultmapper/processor/parameters/MappingParameters.java
Fix import failing that is caused by unpopulated required authoritySourceFiles field.
- 'authoritySourceFiles' field is marked to be ignored
=> MODDICORE-280 Import is failing due to authoritySourceFiles

NEWS.md, ramls/instance.json, src/test/resources/org/folio/processing/mapping/instance/rules.json
It's needed to have ability to map authority ID into a instance contributor controlled by authority
Extend instance.contributors with authorityId
=> MODDICORE-281 Extend instance contributors schema with Authority ID

pom.xml, ramls/authority.json, src/main/java/org/folio/processing/mapping/defaultmapper/processor/Escaper.java, src/main/java/org/folio/processing/mapping/defaultmapper/processor/Processor.java, src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java, src/test/java/org/folio/processing/mapping/AuthorityMappingTest.java, src/test/java/org/folio/processing/mapping/functions/NormalizationFunctionTest.java, src/test/resources/org/folio/processing/mapping/authority/authorityRules.json, src/test/resources/org/folio/processing/mapping/authority/mappedRecordWithSourceFileAt001And010.json, src/test/resources/org/folio/processing/mapping/authority/mappedRecordWithSourceFileAt010.json, src/test/resources/org/folio/processing/mapping/authority/mappedRecordWithSourceFileAt010WithMultipleSubfields.json, src/test/resources/org/folio/processing/mapping/authority/parsedRecordWithSourceFileAt001And010.json, src/test/resources/org/folio/processing/mapping/authority/parsedRecordWithSourceFileAt010.json, src/test/resources/org/folio/processing/mapping/authority/parsedRecordWithSourceFileAt010WithMultipleSubfields.json
Implement rules for mapping Authority Source File Id. As not all the requirements can be met using the currently existing MARC rule mapping implementation, new flag was added. 
[MODSOURMAN-821](https://issues.folio.org/browse/MODSOURMAN-821)
- Flag "skipIfTargetIsAssigned" indicating whether a rule should be skipped when target value is already assigned added
- Authority Source File Id mapping tests and corresponding json files for them added
- Existing implementation of SET_AUTHORITY_SOURCE_FILE_ID function changed to use MARC field value instead of the rule parameter
=> MODSOURMAN-821 Assign each authority record to an Authority Source file list

ramls/authority.json, src/main/java/org/folio/processing/mapping/defaultmapper/MarcToAuthorityMapper.java, src/main/java/org/folio/processing/mapping/defaultmapper/processor/Processor.java, src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java, src/test/java/org/folio/processing/mapping/AuthorityMappingTest.java, src/test/java/org/folio/processing/mapping/functions/NormalizationFunctionTest.java, src/test/resources/org/folio/processing/mapping/authority/authorityRules.json, src/test/resources/org/folio/processing/mapping/authority/mappedRecordWithSourceFileAt001.json, src/test/resources/org/folio/processing/mapping/authority/mappedRecordWithSourceFileAt001And010.json, src/test/resources/org/folio/processing/mapping/authority/mappedRecordWithSourceFileAt010WithMultipleSubfields.json, src/test/resources/org/folio/processing/mapping/authority/mappedRecordWithoutSourceFile.json, src/test/resources/org/folio/processing/mapping/authority/parsedRecordWithSourceFileAt001.json, src/test/resources/org/folio/processing/mapping/authority/parsedRecordWithoutSourceFile.json
**Purpose**
It's needed to have information of an Authority Natural ID to use it in a link in the $0 subfield of linked bib fields. This Natural ID should be the ID by which Authority File ID was determined.
Also, it's needed because requirements were not clear for populating Source File ([MODINVSTOR-892](https://issues.folio.org/browse/MODINVSTOR-892)) it was just check 001 and 010$a fields but was changed to check first 010$a and then check 001.
JIRA: https://issues.folio.org/browse/MODDICORE-283
**Approach**
- move logic from SET_AUTHORITY_SOURCE_FILE_ID to MarcToAuthorityMapper
- check first 010$a subfield and if it is not suited by criteria for identifying Authority File ID then check 001 field
- when Authority File ID is identified also populate `naturalId` field of authority
- if …
=> MODDICORE-283 Change logic of sourceFileId populating by adding Authority Natural ID

src/main/resources/log4j2-json.properties
Adjust logging configuration to display datetime in a proper format
Changed config files
=> [MODDATAIMP-736] Adjust logging configuration to display datetime in a proper format

NEWS.md, src/test/java/org/folio/processing/mapping/mapper/writer/JsonBasedWriterUnitTest.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
The main goal is to verify and check if Order/OrderLine entity mapped successfully.
All changes for mapping profile are added there: https://issues.folio.org/browse/UIDATIMP-1333.
Tests on complex fields added.
JIRA: https://issues.folio.org/browse/MODDICORE-290
=> MODDICORE-290: Extend Mapper for Order/OrderLines

pom.xml, src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java, src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java
Use links data that come from mod-source-records-storage to update MARC bib record according to requirements
Delete links from links data if some of the cases occurred. Mod-source-record-storage will make a call to update links in mod-entities-links
Implement custom MarcRecordModifier
[MODDICORE-293](https://issues.folio.org/browse/MODDICORE-293)
=> MODDICORE-293 Handle bib-authority link when user updates a bib record via data import

NEWS.md, src/main/java/org/folio/processing/mapping/MappingManager.java, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/mapping/manager/MappingManagerUnitTest.java, src/test/java/org/folio/processing/mapping/manager/TestOrder.java, src/test/java/org/folio/processing/mapping/manager/TestOrderWriter.java, src/test/java/org/folio/processing/mapping/manager/TestOrderWriterFactory.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
Allow for mapping the vendor, material supplier, and access provider based on CODE in MARC record. For not CODE income values return blank value
Added CODE (ID) of the organization to AcceptedValues of incoming vendor, material supplier or access provider, added functional that returns blanks if incoming value is not in acceptedValues (only for vendor, material supplier and access provider) 
Jira: https://issues.folio.org/browse/MODDICORE-303
=> [MODDICORE-303] Allow for mapping the vendor, material supplier, and access provider based on CODE in MARC record

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Delete link on linked field removal
- add check that subfield $0 ends with authorityNaturalId from link
[MODDICORE-308](https://issues.folio.org/browse/MODDICORE-308)
=> MODDICORE-308 Link wasn't deleted when user deletes linked repeatable field via "Data import" update

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Fix adding uncontrolled subfields for controlled fields
- add 'null' check for existing subfield. Create on absence
[MODDICORE-309](https://issues.folio.org/browse/MODDICORE-309)
=> MODDICORE-309 Error when adding uncontrolled subfield in linked "MARC bib" record upon data import

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Remove $9 subfield on field unlinking
- Add $9 subfield removal on field unlinking
[MODDICORE-311](https://issues.folio.org/browse/MODDICORE-311)
=> MODDICORE-311 Unlinked field looks like linked on UI when update/import "MARC Bib" record when $9 is included in the imported file

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Add uncontrolled subfields removal for linked fields on subfields removal.
Add uncontrolled subfields removal for linked fields on subfields removal.
[MODDICORE-309](https://issues.folio.org/browse/MODDICORE-309)
=> Add uncontrolled subfields removal for linked fields on subfields removal

src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
Validate mappingRule for the repeatable field by the "required" field (do not map if the required value is empty)
Added new conditions and covered with tests
Need to remove redundant "RequiredFields" enum and use the "required" field instead in further releases
=> [MODDICORE-306] Order import: fix product identifier problem with ISBN field

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java, src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Fix bug when: Link is removed from field when updating/deleting "$0" in linked "MARC bib" field upon data import if field mapping profile does not allow "$0" update
Modify linking check to get $0 from existing record instead of incoming when $0 cannot be modified according to mapping
=> MODDICORE-319 Modify linking check when $0 cannot be modified according to mapping

src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
to fix order line product identifiers field mapping when a mapping rule "value" field intermittently is not stored in a mapping profile for some of the product identifiers subfield (e.g qualifier)
* add check for mapping rule "value" field is null to return MissingValue on processing such mapping rule
* add test
[MODDICORE-305](https://issues.folio.org/browse/MODDICORE-305)
=> MODDICORE-305 - Order import: fix product identifier mapping problem with multiple product ID TYPES

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java, src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Retain a link if a repeatable field is protected and a user tries to update or delete it.
* Change logic of link detection to also check 
** $9 == link.authorityId
** $0 endsWith link.naturalId
=> MODDICORE-327 Retain link if repeatable field is protected

NEWS.md, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
to fix call number field mapping for inventory holdings/item records when incoming MARC record contains multiple copies of the specified MARC field or multiple specified subfields in that MARC field.
For example when incoming record contains the following fields:
> 050 14 $aB3199.A33 $bP7613 2000a $aTA418.9.C6
> 050 14 $aZ5853.M38 $bG37 1993
> 
then for this specified mapping 050$a " " 050$b mapped "callNumber" field should contain: B3199.A33 P7613 2000a
* change the approach of subfields data retrieving to get data for subfields with same name (code) separately per each subfield instead of getting it as concatenated value.
For the simple filed rule return StringValue that contains data only from 1-st specified subfield.
* add test …
=> MODDICORE-322 - Multiple 050 fields or subfields all map to Holdings/Item Call Number if Holdings/Item Mapping is set to 050$a or 050$a " " 050$b

pom.xml, src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Update links interactions according to 'instance-authority-links' interface change to 2.0
Update raml InstanceLinkDtoCollection dto with removing field/subfields, adding linkingRuleId
Add linking rules to constructor, they will be needed to identify linked subfields
[MODDICORE-320](https://issues.folio.org/browse/MODDICORE-320)
=> MODDICORE-320: Changed instanceLink DTO according to recent changes

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
- Remove hardcoded bib 'controllable' tags
- Use bib tags from linking rules{}
https://issues.folio.org/browse/MODDICORE-325
=> MODDICORE-325 Use linkable tags from linking rules, not hardcoded

src/main/java/org/folio/processing/mapping/mapper/writer/marc/LinkFull.java, src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java, src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Fix handling links in repeatable fields. Fix $9 subfield removal on linkable (not linked) repeatable fields.
- Fix handling links in repeatable fields
- Fix $9 subfield removal on linkable (not linked) repeatable fields
- Refactor links/linking rules interaction
- Fix repeatable/single field logic in tests
[MODDICORE-335](https://issues.folio.org/browse/MODDICORE-335)
=> MODDICORE-335 Controlled subfields of Second repeatable and linked field could be overwritten by "Data import" update.

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifier.java, src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Properly handle simultaneous repeatable linked fields (with same tag) updates with custom mapping details
- Add every incoming field processing in case mapping details present
- Add $9 subfield clearing in case 'updateSubfields' was avoided and field added directly
[MODDICORE-346](https://issues.folio.org/browse/MODDICORE-346)
=> MODDICORE-346 Improve handling $0 and $9 in repeatable fields

src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcBibRecordModifierTest.java
Fix custom mapping details updates for "*" tag value. Fix keeping links on updates with custom mapping details
[MODDICORE-349](https://issues.folio.org/browse/MODDICORE-349)
- Add '*' condition to 'tag' check in field match check
- Add link keep check for non-updated field in custom mapping details fields handling
=> MODDICORE-349 Fix handling field updates for mapping details tag '*' in repeatable

NEWS.md, ramls/settings/authoritysourcefile.json, ramls/settings/location.json, src/main/java/org/folio/processing/mapping/MappingManager.java, src/main/java/org/folio/processing/mapping/mapper/FactoryRegistry.java, src/main/java/org/folio/processing/mapping/mapper/Mapper.java, src/main/java/org/folio/processing/mapping/mapper/mappers/AbstractMapper.java, src/main/java/org/folio/processing/mapping/mapper/mappers/HoldingsMapper.java, src/main/java/org/folio/processing/mapping/mapper/mappers/ItemMapper.java, src/main/java/org/folio/processing/mapping/mapper/mappers/MapperFactory.java, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/main/java/org/folio/processing/matching/MatchingManager.java, src/main/java/org/folio/processing/matching/entities/PartialError.java, src/main/java/org/folio/processing/matching/matcher/AbstractMatcher.java, src/main/java/org/folio/processing/matching/matcher/HoldingsItemMatcher.java, src/main/java/org/folio/processing/matching/matcher/Matcher.java, src/main/java/org/folio/processing/matching/matcher/MatcherFactory.java, src/test/java/org/folio/processing/mapping/manager/MappingManagerUnitTest.java, src/test/java/org/folio/processing/mapping/mapper/HoldingsMapperTest.java, src/test/java/org/folio/processing/mapping/mapper/ItemMapperTest.java, src/test/java/org/folio/processing/matching/manager/MatchingManagerTest.java, src/test/java/org/folio/processing/matching/matcher/HoldingsItemMatcherTest.java
Implement multiple mapping and matching
A new Factory was created for the new Multiple Entities in the scope of [MODDICORE-336](https://issues.folio.org/browse/MODDICORE-336). The mechanism for Multiple Holdings will create a new Holdings-entity for each UNIQUE location (multiple fields for holdings should be placed in the same field with permLocId) in the MARC file.
The mechanism for Multiple Holdings will create a new Item-entity for each marc field that defines holdings.permanentLocationId
Added support for multiple matching, setting up ERRORS and amount of non-matched holdings/items in context
=> Multiple mapping and matching

.github/workflows/build-dependants.yml, Jenkinsfile, NEWS.md, pom.xml, src/main/java/org/folio/processing/mapping/defaultmapper/processor/JSManager.java, src/main/java/org/folio/processing/mapping/defaultmapper/processor/Processor.java, src/test/resources/org/folio/processing/pom/pom-sample.xml
_Magration to Java 17._
_Implies migration from Nashorn to GraalVM JS engine_
=> MODDICORE-356: Upgrade data-import-processing-core to Java 17

src/main/java/org/folio/processing/matching/matcher/AbstractMatcher.java, src/test/java/org/folio/processing/matching/matcher/HoldingsItemMatcherTest.java
Fix journal records processing when single holding is not matched. 
It should a fix for two Karate tests (_FAT-944 Match MARC-to-MARC and update Instances, fail to update Holdings and Items_; _FAT-945 Match MARC-to-MARC and update Instances, Holdings, fail to update Items_)
Set not matched number for single holdings match to properly handle journal records on SRM
=> FAT-6493: Set not matched number for single holdings match

ramls/authority.json
To be able to parse and check source value on mod-inventory for determining whether MARC authority record is being updated on member tenant or not.
Adding enum values.
https://github.com/folio-org/mod-inventory/pull/628
[MODDATAIMP-926](https://issues.folio.org/browse/MODDATAIMP-926)
=> MODDATAIMP-926: Add consortium values into authority source

NEWS.md, src/main/java/org/folio/processing/mapping/mapper/mappers/HoldingsMapper.java, src/test/java/org/folio/processing/mapping/mapper/HoldingsMapperTest.java
Remove distinct by permanentLocationId for multiple Holdings during mapping if Holdings already contain at the context
- Reorder invocation of distinctHoldingsByPermanentLocation in HoldingsMapper class by calling it in case of absence of holdings in the context. 
- Add to context, holdings when holdings exist in context.
=> MODDICORE-366: Remove distinct by permanentLocationId for multiple Holdings during mapping if Holdings already contain at the context

ramls/settings/organization.json
The import of file is completed with errors for orders creation
Add 'isDonor' field to organization schema
=> [MODDICORE-373] Add 'isDonor' field to organization schema

ramls/settings/electronicaccessrelationship.json, ramls/settings/loantype.json
Schemas updated in mod-inventory-storage and caused errors constructing mapping parameters in SRM
We'll need a better handling of such cases, but this should resolve the immediate problem
=> Update loanType and electronicaccessrelationship schemas

NEWS.md, src/main/java/org/folio/processing/events/EventManager.java, src/main/java/org/folio/processing/events/services/processor/EventProcessorImpl.java, src/test/java/org/folio/processing/events/EventManagerUnitTest.java
The main purpose is to clear DataImportEventPayload after Multiple Optimistic Locking errors are revealed.
Removed "OL_ACCUMULATIVE_RESULTS" after invoking handle()-method.
JIRA: https://issues.folio.org/browse/MODDICORE-382
This PR should be merged BEFORE https://github.com/folio-org/mod-inventory/pull/639 will be merged.
=> MODDICORE-382: Remove from the payload extra key after Multiple Optimistic Locking error reveals

NEWS.md, pom.xml, src/main/java/org/folio/processing/events/services/processor/EventProcessorImpl.java, src/main/java/org/folio/processing/mapping/MappingManager.java, src/main/java/org/folio/processing/mapping/mapper/reader/matcher/AcceptedValuesMatcher.java, src/main/java/org/folio/processing/mapping/mapper/reader/matcher/StatisticalCodeAcceptedValuesMatcher.java, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/main/java/org/folio/processing/mapping/mapper/writer/common/FieldPathIterator.java, src/test/java/org/folio/processing/mapping/manager/MappingManagerUnitTest.java, src/test/java/org/folio/processing/mapping/mapper/reader/matcher/StatisticalCodeAcceptedValuesMatcherTest.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
to fix statistical code mapping that includes 'else' in a field mapping profile, so that statistical code in the 'else' mapping statement has been applied if an incoming MARC record does not contain a MARC field providing statistical code data for mapping. 
In addition, statistical code and name comparison for accepted value determination needs to be changed to be case-sensitive.
* change statistical code mapping logic to support statistical code mapping by code or full name retrieved from incoming MARC field, or using stat code specified in the 'else' part of mapping if there is no incoming MARC field containing statistical code data. Change logic for stat code accepted value determination to perform a case-sensitive comparison.
* add and update tests …
=> MODDICORE-368 - 'else' statement in Field Mapping Profile for Statistical Code is ignored

NEWS.md, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
Fix Item creation when Statistical Code value is empty
Remove hardcoded empty object when retrieved value is MissingValue
[MODINV-906](https://issues.folio.org/browse/MODINV-906)
=> MODINV-906: Fix Item creation when Statistical Code value is empty

ramls/settings/servicepoint.json
it's necessary to update servicepoint schema with "holdShelfClosedLibraryDateManagement" field to fix import on the consortia sprint testing env
=> Update servicepoint schema with "holdShelfClosedLibraryDateManagement" field

ramls/settings/authoritysourcefile.json
update authoritysourcefile  schema to fix import on the consortia sprint testing env
=> MODDATAIMP-979 - Updated authoritysourcefile schema with consortium value

ramls/settings/authoritysourcefile.json
Accomodate for authority-source-files api changes
Add 'consortium' to source enum of authority-source-file dto
[MODSOURMAN-1115](https://issues.folio.org/browse/MODSOURMAN-1115)
=> MODSOURMAN-1115 Accomodate for authority-source-files api changes

ramls/settings/authoritysourcefile.json
Accomodate for authority-source-files api optimistic locking changes
Add _version field to authoritysourcefile
=> MODSOURMAN-1116 Accomodate for authority-source-files api optimistic locking changes

NEWS.md, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/events/services/publisher/KafkaEventPublisherTest.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
[MODDICORE-388](https://folio-org.atlassian.net/browse/MODDICORE-388) Allow to map vendor details with code that contains brackets during order creation
remove unnecessary parentheses
=> MODDICORE-388 Allow to map vendor details with code that contains brackets during order creation

NEWS.md, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
The main goal is to left "relationshipId"-field as empty if the value is invalid (can't map via acceptedValues.)
Added "relationshipId" to the 'NEEDS_VALIDATION_BY_ACCEPTED_VALUES'-list.
JIRA: https://folio-org.atlassian.net/browse/MODDICORE-406
=> MODDICORE-406: Relationship ID incorrect mapping

.github/workflows/build-dependants.yml
bump actions/upload-artifact to v4 to fix workflow failure caused by actions/upload-artifact-v2 deprecation
=> Bump actions/upload-artifact to v4

NEWS.md, src/main/java/org/folio/processing/mapping/MappingManager.java, src/main/java/org/folio/processing/mapping/mapper/reader/record/marc/MarcRecordReader.java, src/test/java/org/folio/processing/mapping/manager/MappingManagerUnitTest.java, src/test/java/org/folio/processing/mapping/reader/MarcRecordReaderUnitTest.java
support po line "donorOrganizationIds" field mapping when MARC field mapping syntax set
* populate mapping profile with donor organizations' data
* add check for "donorOrganizationIds" field to return empty value in case incoming value does not match existing organization data
* add tests
[MODDICORE-413](https://issues.folio.org/browse/MODDICORE-413)
=> MODDICORE-413 - Adjust mapping of order to fill in donor information

NEWS.md, README.md, pom.xml, ramls/authorityExtended.json, ramls/relatedHeading.json, src/main/java/org/folio/processing/mapping/defaultmapper/MarcToAuthorityMapper.java, src/main/java/org/folio/processing/mapping/defaultmapper/MarkToAuthorityExtendedMapper.java, src/main/java/org/folio/processing/mapping/defaultmapper/RecordMapperBuilder.java, src/main/java/org/folio/processing/mapping/defaultmapper/processor/LoaderHelper.java, src/main/java/org/folio/processing/mapping/defaultmapper/processor/Processor.java, src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java, src/test/java/org/folio/processing/mapping/AuthorityExtendedMappingTest.java, src/test/resources/org/folio/processing/mapping/authority/mappedRecordExtended.json, src/test/resources/org/folio/processing/mapping/authority/parsedRecordExtended.json
There is an extended Authority Mapping introduced to support advanced references classification in 4xx-5xx fields:
broader terms ($wg tag)
narrower terms ($wh tag)
earlier headings ($wa tag)
later headings ($wb tag)
Including this functionality requires generating AuthorityExtended class and applying MarkToAuthorityExtendedMapper.
=> [MODINV-1071] Extended authorities mapping for Quesnelia

pom.xml
https://folio-org.atlassian.net/browse/MODDICORE-430
data-import-processing-core comes with snappy-java 1.1.10.0 that has four security vulnerabilities:
* https://nvd.nist.gov/vuln/detail/CVE-2023-43642
* https://nvd.nist.gov/vuln/detail/CVE-2023-34455
* https://nvd.nist.gov/vuln/detail/CVE-2023-34453
* https://nvd.nist.gov/vuln/detail/CVE-2023-34454
How can this be fixed?
Upgrade Vertx from 4.5.7 to 4.5.11.
This indirectly upgrades snappy-java from 1.1.10.0 to 1.1.10.5 fixing the vulnerabilities.
RMB 35.3.0 comes with Vert.x 4.5.10 that has the fixed snappy-java version. For an unknown reason data-import-processing-core has used Vert.x to 4.5.7 since it upgraded to RMB 35.3.0: https://folio-org.atlassian.net/browse/MODDICORE-425 = …
=> MODDICORE-430: Vert.x 4.5.11 fixing snappy-java vulnerabilities

README.md, src/main/java/org/folio/processing/mapping/defaultmapper/processor/Processor.java, src/test/resources/org/folio/processing/mapping/authority/mappedRecordExtended.json, src/test/resources/org/folio/processing/mapping/authority/parsedRecordExtended.json
[MODDICORE-436](https://folio-org.atlassian.net/browse/MODDICORE-436)
For ASA customer it is required to apply subFieldDelimiter “--” before tags “x”, “y”, “z”, “v” in 1xx, 4xx and 5xx fields.
subFieldDelimiter "--" mapping is added programmatically for AuthorityExtended instances.
=> MODDICORE-436: Apply "--" subFieldDelimiter to AuthorityExtended fields

README.md, ramls/authorityExtended.json, src/main/java/org/folio/processing/mapping/defaultmapper/processor/Processor.java, src/test/resources/org/folio/processing/mapping/authority/mappedRecordExtended.json, src/test/resources/org/folio/processing/mapping/authority/parsedRecordExtended.json
[MODDICORE-426](https://folio-org.atlassian.net/browse/MODDICORE-426)
[MODDICORE-436](https://folio-org.atlassian.net/browse/MODDICORE-436)
MODDICORE-426:
For ASA customer it is required to exclude subfields “i” and numeric subfields from the mapping for 5xx fields in Authority.
Example:
$w r $i Successor: $a Sri Lanka $4 http://rdaregistry.info/Elements/u/P60686 $0 (DLC)n 80061039 $0 http://id.loc.gov/authorities/names/n80061039 $1 http://id.loc.gov/rwo/agents/n80061039
should be transformed to Sri Lanka, not to Successor: Sri Lanka
MODDICORE-436:
For ASA customer it is required to apply subFieldDelimiter “--” before tags “x”, “y”, “z”, “v” in 1xx, 4xx and 5xx fields.
_How does this change fulfill the purpose?_
_Describe the research stage. Add links to blog posts, patterns, libraries or …
=> MODDICORE-426-436 authorities custom mapping Ramsons

NEWS.md, ramls/instance.json
Add boolean “deleted” field to Instance with default value=false
=> MODINVSTOR-1342: Add "deleted" field to Instance schema

src/main/java/org/folio/processing/events/EventManager.java, src/main/java/org/folio/processing/events/services/processor/EventProcessorImpl.java, src/main/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifier.java, src/test/java/org/folio/processing/events/AbstractRestTest.java, src/test/java/org/folio/processing/events/EventManagerUnitTest.java, src/test/java/org/folio/processing/mapping/mapper/writer/marc/MarcRecordModifierTest.java, src/test/resources/log4j2.properties
This issue was reproduced when the "Subfield" filed in "MARC field protection" equals "*".
The value of all Subfields will be checked for equality with the specified value
[MODDATAIMP-1189](https://folio-org.atlassian.net/browse/MODDATAIMP-1189)
=> MODDATAIMP-1189: Fix update of MARC bibliographic fails with "NullPointerException"

pom.xml, src/main/java/org/folio/processing/matching/loader/query/LoadQueryBuilder.java, src/test/java/org/folio/processing/matching/loader/LoadQueryBuilderTest.java
https://folio-org.atlassian.net/browse/MODDICORE-457
Per @okolawole-ebsco 
Data import job fails with timeout errors when matching MARC records against existing instances by identifiers. Investigation reveals:
Current Generated SQL Structure: 
```
WHERE (get_tsvector(...) @@ tsquery_phrase('"identifierTypeId":"439bfbae-75bc-4f74-9fc7-b2a2d47ce3ef"')) 
AND ((get_tsvector(...) @@ tsquery_phrase('"value":"(OCoLC)on1349275037"')) 
OR (get_tsvector(...) @@ tsquery_phrase('"value":"(OCoLC)1349275037"')))
```
Postgres's query planner cannot determine that filtering by `value` first would be more selective since it's using full-text search. The current CQL structure generates SQL that encourages Postgres to use the less selective `identifierTypeId` filter as the primary index condition.
There is …
=> MODDICORE-457 Enhance CQL Query Gen for Performance During Identifier Matching

NEWS.md, src/main/java/org/folio/processing/events/services/publisher/KafkaEventPublisher.java, src/test/java/org/folio/processing/events/services/publisher/KafkaEventPublisherTest.java
to restrict data import update action from a member tenant for a record/instance located on a central tenant
[MODDICORE-459](https://issues.folio.org/browse/MODDICORE-459)
=> MODDICORE-459 - Fill in permissions header during event sending 
